"""Writes paper/numbers.tex: every number quoted in the prose of main.tex, read from results/ and data/.

Premiums are in AUC points (1 point = 0.01 macro-AUC). The script also re-checks each claim the text makes about
these numbers (for example, that the patient-bootstrap interval is the wider one) and stops if one no longer holds.
Run: python scripts/make_paper_numbers.py
"""
from __future__ import annotations

import json
import math
import re
from functools import partial
from pathlib import Path

import pandas as pd

import analyze

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "numbers.tex"
VARIANTS = {"primary": "uzero_P_base", "clean": "uzero_P_clean", "uone": "uone_P_base"}
LABELS = ["Atelectasis", "Cardiomegaly", "Consolidation", "Edema", "Pleural Effusion"]
DOSE_WORD = {3: "Three", 15: "Fifteen", 100: "Hundred", 500: "FiveHundred"}
N_REGISTERED_TESTS = 64  # unpaired probe/k-NN premiums and membership AUCs written by analyze.py
RAD_DINO_IMAGES, NIH_TEST_IMAGES = 882_775, 25_596  # RAD-DINO training manifest (audit/), NIH official test split


# ----------------------------------------------------------------------------- formatting

def _num(x: float, nd: int) -> str:
    s = f"{x:.{nd}f}"
    if float(s) == 0:
        s = f"{0:.{nd}f}"  # no "-0.00"
    return f"${s}$" if s.startswith("-") else s


def pts(x: float, nd: int = 2) -> str:
    """AUC difference in points (hundredths of AUC)."""
    return _num(100 * x, nd)


def auc(x: float, nd: int = 2) -> str:
    return _num(x, nd)


auc3 = partial(auc, nd=3)


def pval(p: float) -> str:
    if p < 0.001:
        return "$<$0.001"
    if p >= 0.995:
        return "1"
    return f"{p:.2f}" if p >= 0.1 else f"{p:#.2g}"  # '#' keeps a trailing zero: 0.090


def ci(lo: float, hi: float, fmt) -> str:
    a, b = fmt(lo), fmt(hi)
    return f"{a} to {b}" if "-" in a + b else f"{a}--{b}"


def thousands(n: int) -> str:
    return f"{int(n):,}".replace(",", "{,}")


def half_up(x: float) -> int:
    """Round a non-negative share half up (Python's round() rounds half to even)."""
    if x < 0:
        raise ValueError(f"half_up is for non-negative shares, got {x}")
    return math.floor(x + 0.5)


def macro(name: str, value: str) -> str:
    if not re.fullmatch(r"[A-Za-z]+", name):
        raise ValueError(f"LaTeX macro names take letters only: {name!r}")
    return rf"\newcommand{{\{name}}}{{{value}}}"


def merge(*parts: dict) -> dict:
    out: dict = {}
    for part in parts:
        clash = out.keys() & part.keys()
        if clash:
            raise ValueError(f"duplicate macro names: {sorted(clash)}")
        out = {**out, **part}
    return out


def render(values: dict[str, str]) -> str:
    head = "% Generated by scripts/make_paper_numbers.py from results/ and data/. Do not edit by hand."
    return "\n".join([head, *(macro(k, v) for k, v in values.items())]) + "\n"


# ----------------------------------------------------------------------------- claims

def require(ok: bool, claim: str) -> None:
    if not ok:
        raise ValueError(f"a claim in main.tex no longer holds: {claim}")


def _width(interval: list[float]) -> float:
    return interval[1] - interval[0]


def require_bootstrap_wider(contrasts: dict[str, dict]) -> None:
    """Methods and Results say the patient-bootstrap interval is the wider one for every crossover contrast."""
    narrower = [k for k, c in contrasts.items() if _width(c["ci95_boot_sampling_only"]) <= _width(c["ci95"])]
    require(not narrower, f"patient-bootstrap CI not wider than the placebo CI for {narrower}")


def extended_holm(family: dict[str, float], extra: dict[str, float]) -> dict[str, float]:
    """Holm over the registered secondary family plus endpoints that were computed later (PREREG analysis log)."""
    clash = family.keys() & extra.keys()
    if clash:
        raise ValueError(f"endpoint names already in the family: {sorted(clash)}")
    names = [*family, *extra]
    return dict(zip(names, analyze.holm([*family.values(), *extra.values()])))


# ----------------------------------------------------------------------------- sections

def _json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _last(d: pd.DataFrame) -> pd.DataFrame:
    return d[d.step == d.groupby("run").step.transform("max")]


def mean_over_runs(d: pd.DataFrame, cols):
    """Per-dose mean of the two runs; stops unless there is exactly one row per run and dose."""
    counts = d.groupby("dose").run.agg(["size", "nunique"])
    if not ((counts["size"] == 2) & (counts["nunique"] == 2)).all():
        raise ValueError(f"expected one row per run and dose before averaging the runs:\n{counts}")
    return d.groupby("dose")[cols].mean()


def arms(path: Path) -> dict[str, str]:
    g = pd.read_csv(path).set_index("group")
    larger = g.drop(index="E500")
    spread = max(larger[f"prev_{lab}"].max() - larger[f"prev_{lab}"].min() for lab in LABELS)
    sizes = {"NB": "B", "NPbase": "P_base", "NPclean": "P_clean", "NHa": "H_a", "NHb": "H_b", "NEThree": "E3",
             "NEFifteen": "E15", "NEHundred": "E100", "NEFiveHundred": "E500"}
    return {
        "NFrontal": thousands(g.images.sum()), "NPatients": thousands(g.patients.sum()),
        **{k: thousands(g.loc[grp, "images"]) for k, grp in sizes.items()},
        "EFiveHundredPatients": str(g.loc["E500", "patients"]),
        "AgeRange": f"{half_up(larger.age_mean.min())}--{half_up(larger.age_mean.max())}",
        "APRange": f"{half_up(larger.AP_pct.min())}--{half_up(larger.AP_pct.max())}",
        "FemaleLarger": f"{half_up(larger.female_pct.min())}--{half_up(larger.female_pct.max())}",
        "FemaleEFiveHundred": str(half_up(g.loc["E500", "female_pct"])),
        "PrevSpread": str(half_up(spread)),
        "ViewShareHigh": str(half_up(100 * (g.images * g.dose_run1)[["E100", "E500"]].sum()
                                     / (g.images * g.dose_run1).sum())),
        "RadNIHShare": str(half_up(100 * NIH_TEST_IMAGES / RAD_DINO_IMAGES)),
    }


def validity(res: Path) -> dict[str, str]:
    base = res / "final_v2" / VARIANTS["primary"]
    checks = _json(base / "checks_uzero_P_base.json")
    ext = _json(res / "external_reference.json")
    steps = pd.read_csv(base / "arm_auc_uzero_P_base.csv").groupby("run").step.max()
    r1, r2 = checks["run1"], checks["run2"]
    require(all(r[k] for r in (r1, r2) for k in ("adaptation_passed", "no_collapse")), "adaptation and no collapse")
    require(not r1["positive_control_passed"] and not r2["positive_control_passed"],
            "the registered membership score failed the positive control")
    out = {"StepsOne": thousands(steps[1]), "StepsTwo": thousands(steps[2])}
    for tag, r in (("One", r1), ("Two", r2)):
        (p0, p1), (k0, k1) = r["adaptation_probe_auc_step0_final"], r["collapse_knn_auc_step0_final"]
        out |= {f"Adapt{tag}Start": auc3(p0), f"Adapt{tag}End": auc3(p1), f"Knn{tag}Start": auc3(k0),
                f"Knn{tag}End": auc3(k1), f"PosCtl{tag}": auc3(r["positive_control_E500_mia_auc"])}
    proxy, rad = ext["Proxy after Run 1"], ext["RAD-DINO"]
    return out | {
        "ExtN": str(ext["n_test_images"]), "ExtTrainN": thousands(ext["n_train"]),
        "ExtProxy": auc3(proxy["macro_auc"]), "ExtProxyCI": ci(*proxy["ci95"], auc3),
        "ExtRad": auc3(rad["macro_auc"]), "ExtRadCI": ci(*rad["ci95"], auc3),
        "ExtInit": auc3(ext["DINOv2-S (step 0)"]["macro_auc"]),
    }


def premium(res: Path) -> dict[str, str]:
    v2 = res / "final_v2"
    prim = {k: _json(v2 / t / f"primary_{t}.json") for k, t in VARIANTS.items()}
    ll = {k: _json(v2 / t / f"secondary6_loglik_{t}.json") for k, t in VARIANTS.items()}
    require(prim["primary"] == _json(res / "final_v1_asrun" / "primary_uzero_P_base.json"),
            "the corrected analysis reproduces the as-run primary endpoint")
    require_bootstrap_wider({**{f"auc_{k}": c for k, c in prim.items()}, **{f"loglik_{k}": c for k, c in ll.items()}})
    require(not any(c["equivalent"] for c in prim.values()), "equivalence was not shown in any setting")
    require(all(max(c["ci90"][1], c["ci95_boot_sampling_only"][1]) < analyze.MARGIN for c in prim.values()),
            "every interval excludes a premium of +0.5 points")
    require(all(c["delta_x"] < 0 and c["ci95"][1] < 0 and c["ci95_boot_sampling_only"][1] < 0 for c in ll.values()),
            "the log-likelihood fell in every setting and both intervals exclude zero")

    base = v2 / VARIANTS["primary"]
    registered = pd.read_csv(base / "holm_uzero_P_base.csv")
    if not (registered.test.is_unique and len(registered) == N_REGISTERED_TESTS):
        raise ValueError(f"expected {N_REGISTERED_TESTS} unique registered secondary tests, got {len(registered)}")
    family = registered.set_index("test")["p"].to_dict()
    holm = extended_holm(family, {"endpoint4": prim["clean"]["p"], "endpoint5": prim["uone"]["p"],
                                  "endpoint6": ll["primary"]["p"]})
    final = _last(pd.read_csv(base / "deltas_uzero_P_base.csv"))
    probe = final[final.kind == "probe"]
    finals = {f"run{r}_step{s}" for r, s in zip(final.run, final.step)}
    tests = [(re.match(r"delta_(probe|knn)_(run\d_step\d+)_", t), p) for t, p in holm.items()]
    require(all(p >= 0.05 for m, p in tests if m and m.group(1) == "knn"), "the k-NN premium was never significant")
    require(all(p >= 0.05 for m, p in tests if m and m.group(2) not in finals),
            "no premium at 35% of training survived correction")
    low = probe[probe.dose.isin([3, 15])].delta
    e500 = probe[probe.arm == "E500"].set_index("run")
    adj = _last(pd.read_csv(base / "deltas_adjusted_uzero_P_base.csv"))
    adj500 = adj[adj.arm == "E500"].set_index("run").adjusted_delta
    require(bool((e500.delta < 0).all() and (e500.hi95 < 0).all() and (adj500 < 0).all()),
            "both runs lost AUC at dose 500, before and after baseline adjustment")

    def drop(x: float) -> str:  # a fall, written as a positive number of points
        return pts(-x, nd=1)

    arm_final = _last(pd.read_csv(base / "arm_auc_uzero_P_base.csv")).set_index(["arm", "run"]).probe_auc
    out = {"MarginPts": pts(analyze.MARGIN, nd=1), "HolmM": str(len(holm)),
           "LowRange": ci(low.min(), low.max(), pts),
           "LowCIMax": pts(probe[probe.dose.isin([3, 15])].hi95.max(), nd=1),
           "EFiveHundredRunGap": pts(abs(arm_final[("E500", 1)] - arm_final[("E500", 2)]), nd=1),
           "HbRunGap": pts(abs(arm_final[("H_b", 1)] - arm_final[("H_b", 2)]), nd=1)}
    for tag, key in (("Prim", "primary"), ("Clean", "clean"), ("Uone", "uone")):
        c = prim[key]
        out |= {f"{tag}Delta": pts(c["delta_x"]), f"{tag}CI": ci(*c["ci90"], pts),
                f"{tag}BootCI": ci(*c["ci95_boot_sampling_only"], pts), f"{tag}P": pval(c["p"])}
    for tag, key in (("", "primary"), ("Clean", "clean"), ("Uone", "uone")):
        c = ll[key]
        out |= {f"LLDrop{tag}": f"{-c['delta_x']:.3f}"}
    c = ll["primary"]
    out |= {"LLCI": ci(-c["ci95"][1], -c["ci95"][0], auc3),
            "LLBootCI": ci(-c["ci95_boot_sampling_only"][1], -c["ci95_boot_sampling_only"][0], auc3),
            "LLP": pval(c["p"]), "LLHolm": pval(holm["endpoint6"])}
    matched = _json(res / "amendment10" / "matched.json")
    require(matched["verdict"].startswith("a premium above 0.5 points is excluded"),
            "Amendment 10 rule: a premium above 0.5 points is excluded also with matched probes")
    out |= {"MatchedDelta": pts(matched["delta"]), "MatchedCI": ci(*matched["ci90"], pts)}
    hundred = probe[probe.dose == 100].set_index("run").delta  # Run 1: E100; Run 2: H_a (the dose-100 arm)
    adj100 = adj[(adj.dose == 100) & (adj.run == 1)].adjusted_delta.iloc[0]
    out |= {"UnpairedHundredOne": pts(hundred.loc[1]), "UnpairedHundredTwo": pts(hundred.loc[2]),
            "EHundredHarder": pts(adj100 - hundred.loc[1], nd=1)}  # E100 minus H before training, sign flipped
    require(hundred.loc[1] - adj100 < 0, "E100's images were harder than the held-out arms before training")
    for tag, run in (("One", 1), ("Two", 2)):
        r = e500.loc[run]
        step = int(final[final.run == run].step.iloc[0])
        out |= {f"EFiveHundred{tag}": pts(r.delta), f"EFiveHundred{tag}CI": ci(r.lo95, r.hi95, pts),
                f"EFiveHundred{tag}Drop": drop(r.delta), f"EFiveHundred{tag}AdjDrop": drop(adj500.loc[run]),
                f"EFiveHundred{tag}Holm": pval(holm[f"delta_probe_run{run}_step{step}_E500"])}
    return out


def detection(res: Path) -> dict[str, str]:
    mia = _last(pd.read_csv(res / "final_v2" / VARIANTS["primary"] / "mia.csv"))
    asrun = _last(pd.read_csv(res / "final_v1_asrun" / "mia.csv"))
    head = pd.read_csv(res / "amendment6" / "proxy_head_mia.csv")
    head = mean_over_runs(head[head.calibration == "none"], ["mia_auc", "tpr_at_1pct_fpr"])
    # The outside auditor's score: backbone invariance against the initial encoder, at every dose (the as-run file
    # is the one that scored the dose-100 arm against step 0).
    auditor = asrun[(asrun.score == "inv") & (asrun.reference == "step0")]
    twin = mia[(mia.score == "inv") & (mia.reference == "partner_run")].set_index("run")
    ce = mean_over_runs(mia[mia.score == "dino_ce"], "mia_auc")
    require(sorted(auditor.dose.unique()) == [3, 15, 100, 500], "the auditor's score covers all four doses")
    require(bool((twin.mia_auc > auditor[auditor.dose == 100].mia_auc.max()).all()),
            "the twin run detects dose-100 exposure better than the initial-encoder reference")
    out = {"AuditorRange": ci(auditor.mia_auc.min(), auditor.mia_auc.max(), auc),
           "AuditorMax": auc(auditor.mia_auc.max()),
           "CEHundred": auc(ce.loc[100]), "CEFiveHundred": auc(ce.loc[500])}
    for tag, run in (("One", 1), ("Two", 2)):
        out |= {f"Twin{tag}": auc(twin.loc[run].mia_auc), f"Twin{tag}TPR": f"{100 * twin.loc[run].tpr_at_1pct_fpr:.1f}"}
    for dose, word in DOSE_WORD.items():
        out |= {f"Head{word}": auc(head.loc[dose].mia_auc)}
    nulls = _json(res / "amendment9" / "nulls.json")
    require(nulls["verdict"].endswith("weak exposure signal"), "Amendment 9 rule: the auditor signal counts as weak")
    for tag, (inv, hd) in zip(("One", "Two"), zip(nulls["invariance_step0_reference"], nulls["head_score"])):
        out |= {f"NullInv{tag}": auc(inv["auc"]), f"NullHead{tag}": auc(hd["auc"])}
    return out | {f"HeadTPR{DOSE_WORD[d]}": f"{100 * head.loc[d].tpr_at_1pct_fpr:.1f}" for d in (100, 500)}


def raddino(res: Path) -> dict[str, str]:
    bridge = _json(res / "bridge" / "bridge.json")
    head = _json(res / "amendment6" / "raddino_head.json")
    a7 = _json(res / "amendment7" / "summary.json")
    size = _json(res / "amendment7" / "size_check.json")
    require(bridge["gate_passed"], "the exchangeability gate passed")
    require(bridge["mia_ci95"][0] < 0.5 < bridge["mia_ci95"][1], "the backbone score does not separate the pools")
    require(head["mia_ci95"][0] > head["mde_auc"], "the head score exceeds the minimal detectable AUC")
    require(a7["verdict"].startswith("memorisation"), "the Amendment 7 rule reads the result as memorisation")
    rerun, low = _json(res / "amendment8" / "raddino_head.json"), _json(res / "amendment8" / "raddino_head_lowpass224.json")
    require(abs(rerun["mia_auc"] - head["mia_auc"]) < 0.005, "the laptop re-run reproduces the Amendment 6 AUC")
    require(low["mia_auc"] > low["mde_auc"] and low["mia_ci95"][0] > 0.5,
            "Amendment 8 rule: the low-passed AUC stays above the detectable AUC and its CI excludes 0.5")
    ctl = [a7["proxies"]["run1"], a7["proxies"]["run2"]]
    out = {"NMembers": str(bridge["n_members"]), "NNonmembers": str(bridge["n_nonmembers"]),
           "GateAUC": auc(bridge["gate_auc"]), "GateCI": ci(*bridge["gate_ci95"], auc),
           "RadBackbone": auc(bridge["mia_auc_calibrated"]), "RadBackboneCI": ci(*bridge["mia_ci95"], auc),
           "MDE": auc3(bridge["mde_auc"]), "RadHead": auc(head["mia_auc"]), "RadHeadCI": ci(*head["mia_ci95"], auc),
           "SizeWidth": auc(size["auc_width"]), "SizeHeight": auc(size["auc_height"]),
           "ModalAUC": auc(size["head_auc_modal_size"]), "ModalCI": ci(*size["head_auc_modal_size_ci95"], auc),
           "ModalMembers": str(size["n_modal_members"]), "ModalNonmembers": str(size["n_modal_nonmembers"]),
           "RadHeadLow": auc(low["mia_auc"]), "RadHeadLowCI": ci(*low["mia_ci95"], auc)}
    pools = _json(res / "amendment9" / "pools.json")
    require(pools["verdict"].startswith("pools not separable"), "Amendment 9 rule: pools not separable")
    out |= {"IntensityAUC": auc(pools["intensity_statistics"]["auc"]), "LabelsAUC": auc(pools["labels14"]["auc"])}
    for tag, c in zip(("One", "Two"), ctl):
        out |= {f"Ctl{tag}": auc(c["auc"]), f"Ctl{tag}CI": ci(*c["auc_ci95"], auc),
                f"Diff{tag}": auc(c["diff"]), f"Diff{tag}CI": ci(*c["diff_ci95"], auc)}
    return out


def build(root: Path = ROOT) -> dict[str, str]:
    res = root / "results"
    return merge(arms(root / "data" / "group_summary.csv"), validity(res), premium(res), detection(res), raddino(res))


def main() -> None:
    OUT.write_text(render(build(ROOT)), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
